export const Types = {
  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  CREATE_NEW_USERS: "CREATE_NEW_USERS",
  DELETE_USER: "DELETE_USER",
  USER_ERROR: "USER_ERROR",
};
